import { StyleSheet } from 'react-native-unistyles'

export const animStyles = StyleSheet.create((theme) => ({
  scene: {
    width: '100%',
    alignItems: 'center',
    gap: 8,
    overflow: 'visible',
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '85%',
    gap: 8,
    marginBottom: 16,
  },
  inputField: {
    flex: 1,
    backgroundColor: 'rgba(255,255,255,0.1)',
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
  },
  inputText: {
    fontSize: 15,
    color: '#ffffff',
  },
  addButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: theme.colors.tint,
    justifyContent: 'center',
    alignItems: 'center',
  },
  addButtonText: {
    fontSize: 22,
    color: '#ffffff',
    fontWeight: 'bold',
  },
  listItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.1)',
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 12,
    width: '85%',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.15)',
  },
  listItemFull: {
    width: '100%',
  },
  checkbox: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: theme.colors.tint,
    marginRight: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkmarkText: {
    color: theme.colors.tint,
    fontSize: 14,
    fontWeight: 'bold',
  },
  itemName: {
    flex: 1,
    fontSize: 15,
    color: '#ffffff',
  },
  qtyBadge: {
    backgroundColor: 'rgba(76,175,80,0.2)',
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 3,
    marginLeft: 8,
    overflow: 'hidden',
  },
  qtyText: {
    fontSize: 13,
    fontWeight: 'bold',
    color: theme.colors.tint,
  },
  qtyFlash: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderRadius: 10,
  },
  qtyFlashGreen: {
    backgroundColor: 'rgba(76,175,80,0.5)',
  },
  qtyFlashOrange: {
    backgroundColor: 'rgba(255,152,0,0.5)',
  },
  zoneLabel: {
    flexDirection: 'row',
    width: '85%',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  zoneLabelTextActive: {
    fontSize: 11,
    fontWeight: 'bold',
    color: 'rgba(255,255,255,0.7)',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  zoneLabelTextDim: {
    fontSize: 11,
    color: 'rgba(255,255,255,0.15)',
  },
  swipeDemo: {
    width: '85%',
    alignItems: 'center',
    gap: 8,
    overflow: 'visible',
  },
  itemWrapper: {
    width: '100%',
    position: 'relative',
    overflow: 'visible',
  },
  deleteBg: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    borderRadius: 8,
    backgroundColor: theme.colors.danger,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    paddingHorizontal: 16,
  },
  plusBg: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    borderRadius: 8,
    backgroundColor: theme.colors.tint,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingHorizontal: 16,
  },
  minusBg: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    borderRadius: 8,
    backgroundColor: theme.colors.swipeMinus,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    paddingHorizontal: 16,
  },
  editBg: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    borderRadius: 8,
    backgroundColor: theme.colors.swipeEdit,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingHorizontal: 16,
  },
  editInputField: {
    backgroundColor: 'rgba(255,255,255,0.1)',
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.3)',
    marginBottom: 16,
  },
  editInputText: {
    fontSize: 15,
    color: '#ffffff',
  },
  bgText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#ffffff',
  },
  zoneFlashLeft: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    width: '50%',
    backgroundColor: 'rgba(255,255,255,0.35)',
    borderTopLeftRadius: 8,
    borderBottomLeftRadius: 8,
  },
  zoneFlashRight: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    right: 0,
    width: '50%',
    backgroundColor: 'rgba(255,255,255,0.35)',
    borderTopRightRadius: 8,
    borderBottomRightRadius: 8,
  },
  shoppingItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.1)',
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 12,
    width: '85%',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.15)',
  },
  boughtCircle: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: theme.colors.tint,
    marginRight: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  boughtCheck: {
    color: theme.colors.tint,
    fontSize: 14,
    fontWeight: 'bold',
  },
  startButton: {
    backgroundColor: theme.colors.tint,
    borderRadius: 8,
    paddingVertical: 12,
    width: '85%',
    alignItems: 'center',
    marginTop: 12,
  },
  startButtonText: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: 'bold',
  },
  finishButton: {
    backgroundColor: theme.colors.tint,
    borderRadius: 8,
    paddingVertical: 12,
    width: '85%',
    alignItems: 'center',
  },
  finishButtonText: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: 'bold',
  },
  statusRow: {
    marginBottom: 8,
  },
  statusText: {
    fontSize: 14,
    color: 'rgba(255,255,255,0.6)',
  },
  dialog: {
    backgroundColor: 'rgba(30,30,30,0.95)',
    borderRadius: 14,
    padding: 20,
    width: '80%',
    marginTop: 12,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.15)',
  },
  dialogTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#ffffff',
    textAlign: 'center',
    marginBottom: 6,
  },
  dialogMessage: {
    fontSize: 14,
    color: 'rgba(255,255,255,0.6)',
    textAlign: 'center',
    marginBottom: 16,
  },
  dialogButtons: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 24,
  },
  dialogCancel: {
    fontSize: 15,
    color: 'rgba(255,255,255,0.5)',
  },
  dialogConfirm: {
    fontSize: 15,
    fontWeight: 'bold',
    color: theme.colors.tint,
  },
  statsRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 12,
  },
  statBox: {
    flex: 1,
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
  },
  statNumber: {
    fontSize: 22,
    fontWeight: 'bold',
    color: theme.colors.tint,
  },
  statLabel: {
    fontSize: 11,
    color: 'rgba(255,255,255,0.5)',
    marginTop: 2,
  },
  historyCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 12,
    width: '85%',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
  },
  historyDate: {
    fontSize: 14,
    color: '#ffffff',
  },
  historyInfo: {
    fontSize: 14,
    color: theme.colors.tint,
    fontWeight: '600',
  },
}))
